### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by dhruvshan** [ViacheslavBobrov/Muse_Neuromore#2]
I tried running the stream_data.py program and get an error message of " IndexError: list index out of range ".

**Comment by paulabrennan** [comment]
Me too. But only if there's nothing streaming from BlueMuse. So maybe that's your problem.

**Comment by maren-keld** [comment]
Same here. I got like 1 second of stream then stops and i get this:

Start streaming data to 126.0.0.1:4545 for 3600 seconds
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/Admin/Downloads/stream_data.py", line 36, in _stream_handler
    self.client.send_message(channel, eeg_sample[channel_idx])
IndexError: list index out of range

Did you find any solution? @dhruvshan @ViacheslavBobrov 

I'm using PyCharm with Python 3.7.0 (all packages installed), Muse 2, and BlueMuse 2.0.0.0
